# Generated by Django 4.2.3 on 2023-07-14 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("cod_cliente", models.BigAutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("endereco", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Leitura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datahora", models.DateTimeField(auto_now_add=True)),
                ("tensao", models.FloatField()),
                ("potencia", models.FloatField()),
                ("corrente", models.FloatField()),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="webenergyspy.cliente",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="leitura",
            constraint=models.UniqueConstraint(
                fields=("datahora", "cliente"), name="leitura_ukey"
            ),
        ),
    ]
